### ISSUE TITLE
Use Ram Instead of JFFS

### ISSUE THREAD

**Issue by luisfisherjr** [kabadisha/host-based-vpn-routing#3]
If you are worried about wearing out JFFS try using symlink and writing to ram. This will allow you constantly update websites that load balance for changes without worry about JFFS writes.
```
script_name=$(basename "$0")
ram_file_path="/var/vpndirector_rulelist"
jffs_path="/jffs/openvpn/vpndirector_rulelist"

if [ ! -L $jffs_path ]
then
  logger "$script_name: $jffs_path is not a symlink moving file to $ram_file_path and linking"
  mv $jffs_path $ram_file_path 
  ln -s $ram_file_path $jffs_path
elif [ $(readlink -f $jffs_path) != $ram_file_path ]
then
  logger "$script_name: remaking $jffs_path symlink to point to $ram_file_path"
  rm $jffs_path
  ln -s $ram_file_path $jffs_path
else
  logger "$script_name: no symlink change $jffs_path already points to $ram_file_path"
fi
```

**Comment by kabadisha** [comment]
That is genius! Thanks for the tip.

**Comment by kabadisha** [comment]
Update: I just spent some time trying to implement this and realised that there is a logical catch-22 that makes it impossible :-(

If you implement it this way, each time you reboot the existing rules are lost (as they are on ramdisk). This is fine for the auto-generated rules, since they will be re-created, but it means that any manually defined rules are lost.

The problem is that there is no way to save the rules somewhere persistent only when a manual rule is added. Unless we can find a way to do that, I can't see how this feature can be implemented.

**Comment by luisfisherjr** [comment]
For manually defined rules I just create a text file and parse the data. I believe I store this file in the same folder as the script or a subdirectory as this is persistent

**Comment by luisfisherjr** [comment]
On reboot just have the script regenerate the rules. There is a state that designates initial boot up. I also regenerate my rules every 15 minutes or so and reload them. I pair this with nslookup to deal with endpoints that rotate up addresses or load balance with unpredictable ip. I think I do this with a cron job to kick off every 15 min or so.
